"""Add HomeStat and TechStack models

Revision ID: 5b0b39c517cf
Revises: ec8c522bb17e
Create Date: 2026-03-03 16:34:26.999673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b0b39c517cf'
down_revision: Union[str, Sequence[str], None] = 'ec8c522bb17e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_stats_id'), 'home_stats', ['id'], unique=False)
    op.create_table('tech_stack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tech_stack_id'), 'tech_stack', ['id'], unique=False)
    op.create_index(op.f('ix_tech_stack_name'), 'tech_stack', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tech_stack_name'), table_name='tech_stack')
    op.drop_index(op.f('ix_tech_stack_id'), table_name='tech_stack')
    op.drop_table('tech_stack')
    op.drop_index(op.f('ix_home_stats_id'), table_name='home_stats')
    op.drop_table('home_stats')
    # ### end Alembic commands ###
