"""Add years_of_experience to tech_stack

Revision ID: d55ede6b051f
Revises: 5b0b39c517cf
Create Date: 2026-03-03 19:44:13.559487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd55ede6b051f'
down_revision: Union[str, Sequence[str], None] = '5b0b39c517cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tech_stack', sa.Column('years_of_experience', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tech_stack', 'years_of_experience')
    # ### end Alembic commands ###
