"""Update SiteContent model

Revision ID: ec8c522bb17e
Revises: 0580206d876c
Create Date: 2026-03-03 16:16:22.794005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec8c522bb17e'
down_revision: Union[str, Sequence[str], None] = '0580206d876c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_title', sa.String(), nullable=True),
    sa.Column('typing_tags', sa.JSON(), nullable=True),
    sa.Column('hero_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_content_id'), 'site_content', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_content_id'), table_name='site_content')
    op.drop_table('site_content')
    # ### end Alembic commands ###
